server:
  port: 8881
  context-path: /
spring:
  datasource:
    url: jdbc:mysql://120.79.81.15:3306/diandian?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: R9npsy
nutz:
  paths:
  - sqls